name: Continuous Integration

on:
  pull_request:
    branches: [ develop ]
    
jobs:
  test_pull_request:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run lint
      - run: npm run test:ci
      - run: npm run build
